version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn books.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/amk/web/static
      - media_volume:/home/amk/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  vue:
    build:
      context: ../../books_vue
      dockerfile: Dockerfile.prod
    volumes:
      - vue_dist:/app/dist
    depends_on:
      - web
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/home/amk/web/static
      - media_volume:/home/amk/web/media
      - vue_dist:/app/dist
    depends_on:
      - web
      - vue

volumes:
  postgres_data:
  static_volume:
  media_volume:
  vue_dist: